language: python

python:
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge 
  - conda info -a
  - cp testing/matplotlibrc .

install:
  - conda create -q -n testenv pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file testing/conda_requirements.txt
  - conda remove networkx
  - conda install networkx=1.11  # Needed until nipype GH#2171 is merged
  - pip install git+https://github.com/nipy/nipype  # Needed until nipype 0.14
  - pip install .

before_script:
    - make lint

script:
    - make test
